services:
  ovpn_proxy:
    container_name: ovpn-proxy
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./data/ovpn:/data/ovpn
    environment:
      # - OVPN_CREDENTIALS=/data/ovpn/credentials
      - INIT_TIMEOUT=8
    ports:
      - 8888:8888
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "1.1.1.1"]
      interval: 10s
      timeout: 5s
      retries: 3
